apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
      - name: react3
        image: sudipto003/dummy-react:dev
        ports:
        - containerPort: 80
