apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend2
  template:
    metadata:
      labels:
        app: frontend2
    spec:
      containers:
      - name: react2
        image: sudipto003/dummy-react:production
        ports:
        - containerPort: 80
