version: "3.9"
services:
  web:
    image: flask1
    ports:
      - "3000:3000"
    volumes:
      - ./app2/api:/code/app
    environment:
      FLASK_ENV: development
    links:
      - nodeexp
  nodeexp:
    image: node1
    ports:
      - "8080:8080"